In [1]:
import numpy as np
from pprint import pprint as p

In [2]:
# 创建阵列:
a = np.arange(10,0,-1)
b = np.arange(48).reshape(3,4,4)

In [3]:
# 阵列索引生成的是深副本
a[[0,1,2]].flags.owndata

True

In [4]:
# 结果阵列的数据类型来自原阵列
a[[0,1,2]].dtype == a.dtype

True

In [5]:
# 结果阵列的形状是索引阵列的形状串接上未指明的剩余的轴的形状
print(a[[0,1,2]].shape)
idx = np.array([[0,1],[2,1]])
b.shape, b[idx].shape

(3,)


((3, 4, 4), (2, 2, 4, 4))

In [6]:
# 运行以下命令，观察出错信息
a[[0,1,101]]

IndexError: index 101 is out of bounds for axis 1 with size 10

### 使用多个阵列做索引

In [7]:
# 当使用多个阵列时，多个阵列对应位置的值组合成索引，运行以下命令，观察输出
print(b)
b[[0,1],[0,1],[0,1]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([ 0, 21])

In [8]:
print(b)
b[[0,1],[0,1]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[ 0,  1,  2,  3],
       [20, 21, 22, 23]])

In [9]:
# 当阵列后面有数字时，数字将被广播成与前面的阵列相同的形状
print(b)
b[[0,1],2]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[ 8,  9, 10, 11],
       [24, 25, 26, 27]])

In [10]:
# 当两个阵列形状不同时，尝试广播，无法广播时将出错
b[[0,1],[[1,2],[2,3]]]      # <-- (2,)与(2,2)正常广播
b[[0,1,2],[[1,2],[2,3]]]    # <-- (3,)与(2,2)无法兼容广播，出错

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,2) 

In [11]:
# 索引阵列/切片前面的数据用于按轴的顺序选出指定的数据，供后面的切片/索引阵列索引
print(b)
b[0,1,[1,3]]
#b[0,1,::2]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([5, 7])

In [12]:
print(b)
b[0,1,::2]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([4, 6])

In [13]:
# 切片与右边的数字广播时，切片被转成一维阵列，然后再广播
print(b)
b[::2,0]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[ 0,  1,  2,  3],
       [32, 33, 34, 35]])

In [14]:
# 切片与切片/阵列广播时，所有切片被转成一维阵列，
# 然后左边的转成(X,1)的形状，右边的转成(1,X)的形状，然后广播
print(b)
b[:2,:3]

# [:2,:3] 被转成 [0,1] 和 [0,1,2]
# [0,1] 和 [0,1,2] 被转成 [[0],[1]] 和 [[0,1,2]]
# [[0],[1]] 和 [[0,1,2]] 被广播成：
# np.broadcast_arrays([[0],[1]], np.array([[0,1,2]]))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]]])

In [15]:
print(b)
b[:2,[0,2]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [24, 25, 26, 27]]])

In [16]:
print(b)
b[[0,2],:2]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [17]:
# 用能够被转换成阵列的其它数据类型，作用等同于np.array
print('-->', a[np.array([0,1,2])])
print('-->', a[[0,1,2]])

--> [10  9  8]
--> [10  9  8]


In [18]:
# 但是python的tuple是直接作为索引的，不会被转换成ndarray
print('-->', b[(0,1,2)])      # 等价于 b[0,1,2]
print('-->', b[np.array((0,1,2))], sep='\n', end='')

--> 6
-->
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]

### 用bool阵列来索引

In [19]:
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [21]:
a > 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [20]:
idx = a > 5         # 创建bool阵列
idx.shape, a.shape  # 形状相同

((10,), (10,))

In [26]:
p(a)
p(idx)
p(a[idx])
p(a[:5])

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])
array([ True,  True,  True,  True,  True, False, False, False, False,
       False])
array([10,  9,  8,  7,  6])
array([10,  9,  8,  7,  6])


In [30]:
# 手动创建bool阵列
p(b)
idx = np.array([True, False, False])
p([b.shape, idx.shape])
b[idx]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])
[(3, 4, 4), (3,)]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### 布尔阵列索引另外的阵列时，要求布尔阵列满足以下条件：

#### 布尔阵列的shape 与被索引的阵列的shaepe的头部吻合
#### 布尔阵列的形状: (2,3), 被索引阵列的形状: (2,3,5,5,5) --> 吻合
#### 布尔阵列的形状: (2,3), 被索引阵列的形状: (3,3,5,5,5) --> 不吻合

In [31]:
idx = np.full(b.shape[:2], False, dtype=bool)
print(idx.shape, b.shape)      # bool阵列形状与b阵列头部相同
idx[:,0] = True

print('-->')
print(idx)

print('-->')
print(b)

b[idx]

(3, 4) (3, 4, 4)
-->
[[ True False False False]
 [ True False False False]
 [ True False False False]]
-->
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [32, 33, 34, 35]])

In [9]:
# 对索引结果赋值，用来赋值的值与索引结果的形状必须相同或者兼容广播
print('content:')
print(b[[0,2],[0,1]])
print('shape:')
print(b[[0,2],[0,1]].shape)
print('---')

b[[0,2],[0,1]] = 0                      # 正常广播
b[[0,2],[0,1]] = [1,2,3,4]              # 正常广播
b[[0,2],[0,1]] = [[1,2,3,4],[2,3,4,4]]  # 匹配，不需广播
# b[[0,2],[0,1]] = [1,2]                  # 不能广播，出错

content:
[[1 1 1 1]
 [1 1 1 1]]
shape:
(2, 4)
---
